server:
  port: 8282

spring:
  application:
    name: quiz-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/quizdb

  profiles:
    active: dev

  config:
    import: "configserver:http://localhost:9094"

  cloud:
    function:
      web:
        path: "/functions"

    stream:
      bindings:
        quizCreatedBinding-out-0:
          destination: quiz-created
          group: ${spring.application.name}
          acknowledgement-in-0:
            destination: acknowledge-quiz
            group: ${spring.application.name}

    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      connection-timeout: 10s

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 4
        failureRateThreshold: 50.0
        waitDurationInOpenState: 10s
