server:
  port: 9096

spring:
  application:
    name: question-generator

  data:
    mongodb:
      uri: mongodb://localhost:27017/questionsdb

  profiles:
    active: dev

  config:
    import: "configserver:http://localhost:9094"

  cloud:
    function:
      definition: getQuizBinding
      web:
        path: "/functions"

    stream:
      bindings:
        getQuizBinding-in-0:
          destination: quiz-created
          group: ${spring.application.name}
        getQuizBinding-out-0:
          destination: acknowledge-quiz
          group: ${spring.application.name}

    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      connection-timeout: 10s

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 4
        failureRateThreshold: 50.0
        waitDurationInOpenState: 10s
